[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
# Skip build in dev mode
cmds = []

[start]
cmd = "yarn dev -p 3000"

[healthcheck]
path = "/"
port = 3000
interval = 10
timeout = 5
retries = 5
