import ClientAPI from "@/app/api/api";
import { Footer, Header } from "@/components/Layout";
import type { Metadata } from "next";

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default async function Layout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const homeData = await ClientAPI.getHomeData(locale);
  console.log("Home Data:", homeData);
  const footerSection = homeData?.data?.sections.find(
    (section: any) => section?.id === 6
  );

  return (
    <>
      <Header locale={locale} />
      {children}
      <Footer section={footerSection} locale={locale} />
    </>
  );
}
